name: First Workflow
# event
on: workflow_dispatch
jobs:
  # 自訂義job名稱
  first-job:
    # 選擇環境讓 Steps 執行
    runs-on: ubuntu-latest
    steps:
      # first step
      # step name
      - name: Print greeting
      # command that should be executed in the command line
        run: echo "Hello World!"
      # step name
      - name: Print goodbye
      # command that should be executed in the command line
        run: echo "Done - bye!"

    
